/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.miniprojects.Frames;

import com.miniprojects.connectivity.*;
import com.miniprojects.Frames.*;
import com.miniprojects.beans.AccountBean;

/**
 *
 * @author Usama Sajid
 */
public class AccountantSection extends javax.swing.JFrame {

    /**
     * Creates new form ViewAccountant1
     */
    public AccountantSection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUpdateStudent = new javax.swing.JButton();
        btnDueFees = new javax.swing.JButton();
        btnAddStudent2 = new javax.swing.JButton();
        btnViewStudent1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblLoggedInAccountant = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdateStudent.setText("Update Student");
        btnUpdateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStudentActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, 30));

        btnDueFees.setText("Due Fees");
        btnDueFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDueFeesActionPerformed(evt);
            }
        });
        jPanel1.add(btnDueFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 680, 110, 30));

        btnAddStudent2.setText("Add Student");
        btnAddStudent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudent2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddStudent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 100, 30));

        btnViewStudent1.setText("View Students");
        btnViewStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudent1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewStudent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 110, 30));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/miniprojects/design/import.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 100, 30));
        jPanel1.add(lblLoggedInAccountant, new org.netbeans.lib.awtextra.AbsoluteConstraints(1114, 580, 140, 30));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/miniprojects/design/Accountant Panel.png"))); // NOI18N
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStudent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudent2ActionPerformed
        // TODO add your handling code here:

        AddStudent as = new AddStudent();
        as.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_btnAddStudent2ActionPerformed

    private void btnViewStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStudent1ActionPerformed
        // TODO add your handling code here:

        ViewStudent vs = new ViewStudent();
        vs.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnViewStudent1ActionPerformed

    private void btnUpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStudentActionPerformed
        // TODO add your handling code here:

        UpdateStudent us = new UpdateStudent();
        us.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_btnUpdateStudentActionPerformed

    private void btnDueFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDueFeesActionPerformed
        // TODO add your handling code here:

        DueFees df = new DueFees();
        df.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_btnDueFeesActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        Dashboard db = new Dashboard();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountantSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountantSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountantSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountantSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountantSection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStudent2;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDueFees;
    private javax.swing.JButton btnUpdateStudent;
    private javax.swing.JButton btnViewStudent1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblLoggedInAccountant;
    // End of variables declaration//GEN-END:variables
}
