/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.miniprojects.Frames;

import com.miniprojects.connectivity.*;
import com.miniprojects.Frames.*;
import static com.miniprojects.Frames.ViewStudent.buildTableModel;
import com.miniprojects.beans.StudentBean;
import com.miniprojects.dao.StudentDao;
import com.miniprojects.daoImple.StudentDaoImple;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usama Sajid
 */
public class UpdateStudent extends javax.swing.JFrame {

    /**
     * Creates new form ViewAccountant1
     */
    public UpdateStudent() {
        initComponents();
        setTable();
    }
    
    public void seFields() {
        
        int id = (int) tableUpdate.getValueAt(tableUpdate.getSelectedRow(), 0);
        
        StudentBean sb = new StudentBean();
        sb.setId(id);
        
        StudentDao sd = new StudentDaoImple();
        
        ArrayList<StudentBean> list = (ArrayList<StudentBean>) sd.setAllTxt(sb);
        
        for (StudentBean s1 : list) {
            
            txtName.setText(s1.getName());
            txtEmail.setText(s1.getEmail());
            txtCourse.setText(s1.getCourse());
            txtFees.setText(String.valueOf(s1.getFee()));
            txtPaid.setText(String.valueOf(s1.getPaid()));
            txtDue.setText(String.valueOf(s1.getDue()));
            txtAddress.setText(s1.getAddress());
            txtContact.setText(s1.getContact());
            
        }
        
    }
    
    public void updateStudent() {
        
        int id = (int) tableUpdate.getValueAt(tableUpdate.getSelectedRow(), 0);
        StudentBean sb = new StudentBean();
        
        sb.setName(txtName.getText());
        sb.setEmail(txtEmail.getText());
        sb.setCourse(txtCourse.getText());
        sb.setFee(Integer.parseInt(txtFees.getText()));
        sb.setPaid(Integer.parseInt(txtPaid.getText()));
        sb.setDue(Integer.parseInt(txtDue.getText()));
        sb.setContact(txtContact.getText());
        sb.setAddress(txtAddress.getText());
        sb.setId(id);
        
        StudentDao sd = new StudentDaoImple();
        int update = sd.updateStudent(sb);
        
        if (update != 0) {
            
            JOptionPane.showMessageDialog(null, "Done");
            setTable();
            
        }
        
    }
    
    public void setTable() {
        
        try {
            StudentDao ad = new StudentDaoImple();
            tableUpdate.setModel(buildTableModel(ad.viewStudent()));
        } catch (Exception exe) {
            exe.printStackTrace();
        }
        
    }
    
    public static DefaultTableModel buildTableModel(ResultSet rs) throws SQLException {
        ResultSetMetaData metaData = rs.getMetaData();
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }
        
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }
        return new DefaultTableModel(data, columnNames);
    }
    
    public void clearAlltxt() {
        
        txtName.setText("");
        txtEmail.setText("");
        txtCourse.setText("");
        txtFees.setText("");
        txtPaid.setText("");
        txtDue.setText("");
        txtContact.setText("");
        txtAddress.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCourse = new javax.swing.JTextField();
        txtFees = new javax.swing.JTextField();
        txtPaid = new javax.swing.JTextField();
        txtDue = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        btnUpdate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        updateTable = new javax.swing.JScrollPane();
        tableUpdate = new javax.swing.JTable();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, 200, 30));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 180, 200, 30));
        jPanel1.add(txtCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 240, 200, 30));
        jPanel1.add(txtFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 300, 200, 30));
        jPanel1.add(txtPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 360, 200, 30));
        jPanel1.add(txtDue, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 420, 200, 30));
        jPanel1.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 480, 200, 30));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 540, 180, -1));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/miniprojects/design/updated.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 600, 90, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/miniprojects/design/import.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 80, -1));

        tableUpdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUpdateMouseClicked(evt);
            }
        });
        tableUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableUpdateKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableUpdateKeyReleased(evt);
            }
        });
        updateTable.setViewportView(tableUpdate);

        jPanel1.add(updateTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 650, 370));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/miniprojects/design/Update Student.png"))); // NOI18N
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        AccountantSection as = new AccountantSection();
        as.setVisible(true);
        this.setVisible(false);
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        updateStudent();
        clearAlltxt();
        btnUpdate.setEnabled(false);
        

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tableUpdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableUpdateKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_tableUpdateKeyPressed

    private void tableUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUpdateMouseClicked
        // TODO add your handling code here:

        seFields();
        btnUpdate.setEnabled(true);

    }//GEN-LAST:event_tableUpdateMouseClicked

    private void tableUpdateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableUpdateKeyReleased
        // TODO add your handling code here:

        seFields();
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_tableUpdateKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JTable tableUpdate;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtDue;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFees;
    private javax.swing.JTextField txtName;
    javax.swing.JTextField txtPaid;
    private javax.swing.JScrollPane updateTable;
    // End of variables declaration//GEN-END:variables
}
